### ISSUE TITLE
expires +Ny fails to account for leap years.

### ISSUE THREAD

**Issue by mschout** [kazeburo/Cookie-Baker#10]
I had wrongly assumed that setting the cookie "expires" field to add years (such as '+2y') would advance to the same date in a future year.

It turns out that Cookie::Baker is using  "365 days" as "1 year", which fails if you cross a leap year.

For example, on 2017-03-01, using '+2y' as the expires paramter results in the cookie being sent with the expiration on 2020-02-29.  Off by 1 day due to the fact that 2020 is a leap year.  The correct "+2y" value is 2020-03-01.

I worked around this by doing the calculation externally to CookieBaker, using DateTime and passing the epoch from datetime instead.

I'm not suggesting that Cookie::Baker use DateTime internally, as its a large/heavy module.  But perhaps this is something that should be documented as a CAVEAT in Cookie::Baker?

**Comment by kazeburo** [comment]
When making Cookie :: Baker, I looked at the following code.
They use "365 days" as "1 year".

CGI::Simple
https://metacpan.org/source/MANWAR/CGI-Simple-1.13/lib/CGI/Simple/Util.pm#L104

Apache mod_expires
https://github.com/apache/httpd/blob/trunk/modules/metadata/mod_expires.c#L275

**Comment by mschout** [comment]
Yes, and I understand the reasoning of the "1 year = 365 days" approximation -- Its computationally expensive to figure it out correctly with respect to leap years.  Just suggesting that you document it in the POD.

**Comment by kazeburo** [comment]
Added comments
https://github.com/kazeburo/Cookie-Baker/commit/02fcc62b904491d84b4d7e0e037e9b7a07dc751b
