### ISSUE TITLE
TravisCI is currently failing

### ISSUE THREAD

**Issue by kwry** [kazeburo/Cookie-Baker#16]
CI build always fails.
```
5.12 is not installed; attempting download
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/perl/binaries/ubuntu/16.04/x86_64/perl-5.12.tar.bz2
$ sudo tar xjf perl-5.12.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
https://travis-ci.org/kazeburo/Cookie-Baker/jobs/538527617

I found a report that seems to be the cause.
[Failure with Perl 5.16, 5.18 & 5.20 - Languages / Perl - Travis CI Community](https://travis-ci.community/t/failure-with-perl-5-16-5-18-5-20/2458)

The version of the OS currently used for the build seems to be Xenial (16.04) by default.
If you want to continue testing with the current version of Perl, you need to add `dist: trusty` to your .travis.yml.

**Comment by kazeburo** [comment]
Fixed this issue. Thank you.
