### ISSUE TITLE
missing prereq

### ISSUE THREAD

**Issue by martinthurn-LFT** [kazeburo/Cookie-Baker#6]
Do you need to add URI::Escape to your "requires" list?

[ERROR] MAKE TEST failed:
# Failed test 'use Cookie::Baker;'
# at t/00_compile.t line 4.
# Tried to use 'Cookie::Baker'.
# Error:  Can't locate URI/Escape.pm in @INC (@INC contains: /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/lib /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/arch /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/_build/lib /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/lib /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/arch /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/lib/Cookie/Baker.pm line 7.
# BEGIN failed--compilation aborted at /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/lib/Cookie/Baker.pm line 7.
# Compilation failed in require at (eval 4) line 2.
# BEGIN failed--compilation aborted at (eval 4) line 2.
# Looks like you failed 1 test of 1.

t/00_compile.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
Can't locate Test/Time.pm in @INC (@INC contains: /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/lib /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/arch /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/_build/lib /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/lib /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/arch /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at t/01_bake.t line 3.
BEGIN failed--compilation aborted at t/01_bake.t line 3.
t/01_bake.t ..... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
Can't locate URI/Escape.pm in @INC (@INC contains: /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/lib /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/arch /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/_build/lib /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/lib /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/arch /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/lib/Cookie/Baker.pm line 7.
BEGIN failed--compilation aborted at /home/centos/.cpanplus/5.10.1/build/Cookie-Baker-0.06/blib/lib/Cookie/Baker.pm line 7.
Compilation failed in require at t/02_crush.t line 3.
BEGIN failed--compilation aborted at t/02_crush.t line 3.
t/02_crush.t .... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
## Test Summary Report

t/00_compile.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/01_bake.t   (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/02_crush.t  (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=3, Tests=1,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.08 cusr  0.01 csys =  0.13 CPU)
Result: FAIL

**Comment by kazeburo** [comment]
URI::Escape is not missing. It's exists in cpanfile and META.json
https://metacpan.org/source/KAZEBURO/Cookie-Baker-0.06/cpanfile#L3
https://metacpan.org/source/KAZEBURO/Cookie-Baker-0.06/META.json#L46
